### ISSUE TITLE
[ENHANCEMENT] Check if cache folder exists

### ISSUE THREAD

**Issue by LegitDongo** [PokeAlarm/PokeAlarm#512]
## Description
When the cache folder doesn't exist with file caching on, the program returns an error instead of just creating the cache folder like it probably should
Associated stack trace:

```
Traceback (most recent call last):
  File "start_pokealarm.py", line 231, in <module>
    start_server()
  File "start_pokealarm.py", line 91, in start_server
    parse_settings(os.path.abspath(os.path.dirname(__file__)))
  File "start_pokealarm.py", line 200, in parse_settings
    debug=config['DEBUG']
  File "/PokeAlarm/PokeAlarm/Manager.py", line 61, in __init__
    self.__cache = cache_factory(cache_type, self.__name)
  File "/PokeAlarm/PokeAlarm/Cache/__init__.py", line 11, in cache_factory
    return FileCache(name)
  File "/PokeAlarm/PokeAlarm/Cache/FileCache.py", line 27, in __init__
    with portalocker.Lock(self._file, mode="wb+") as f:
  File "/usr/local/lib/python2.7/dist-packages/portalocker/utils.py", line 195, in __enter__
    return self.acquire()
  File "/usr/local/lib/python2.7/dist-packages/portalocker/utils.py", line 126, in acquire
    fh = self._get_fh()
  File "/usr/local/lib/python2.7/dist-packages/portalocker/utils.py", line 171, in _get_fh
    return open(self.filename, self.mode)
IOError: [Errno 2] No such file or directory: '/PokeAlarm/cache/manager_0.cache'
```

## Why is this enhancement necessary or useful?
Easier for users to go through and devs to help troubleshoot

## How can this enhancement be accomplished?
Adding a check for the folder and creating if it doesn't exist

**Comment by kvangent** [comment]
https://github.com/PokeAlarm/PokeAlarm/pull/606
