### ISSUE TITLE
RDM Quest Format

### ISSUE THREAD

**Issue by LegitDongo** [pokealarm/pokealarm#834]
## Troubleshooting Checklist
- [x] My scanner install is at the most recent version.
- [x] My PokeAlarm install is at the most recent version.
- [x] I've already checked the [FAQ](https://pa.readthedocs.io/en/dev/getting-started/faq.html) and the [Wiki](https://pa.readthedocs.io/en/dev/) already.

## Problem Description
Quests don't work at all when using RDM; they send a different format than PA expects

example webhook:
```json
[
  {
    "message": {
      "pokestop_url": "image url",
      "type": 4,
      "ar_scan_eligible": true,
      "pokestop_id": "xxx",
      "title": "quest_catch_type_grass_plural",
      "with_ar": true,
      "updated": 1655300405,
      "pokestop_name": "xxx",
      "rewards": [
        {
          "type": 2,
          "info": {
            "amount": 5,
            "item_id": 2
          }
        }
      ],
      "template": "challenge_base_catch_grass",
      "latitude": 1.111111,
      "longitude": 1.111111,
      "target": 10,
      "conditions": [
        {
          "info": {
            "pokemon_type_ids": [
              12
            ]
          },
          "type": 1
        }
      ]
    },
    "type": "quest"
  }
]
```

also see [here](https://github.com/RealDeviceMap/RealDeviceMap/blob/56960a6181c62e18d599cad63cd38407d4fd0fc2/Sources/RealDeviceMapLib/Modell/Pokestop.swift) for the repo reference

## Environment
Operating System: ?
Python Version: 3.7
PokeAlarm Version: recent dev
Scanner used: RDM

## Log Output
```
Encountered error while converting webhook data(KeyError: 'quest_type')
Stack trace: 
 Traceback (most recent call last):
  File "/home/x/Documents/PokeAlarm/PokeAlarm/Events/init.py", line 43, in event_factory
    return QuestEvent(message)
  File "/home/x/Documents/PokeAlarm/PokeAlarm/Events/QuestEvent.py", line 44, in init
    self.quest_type_raw = data['quest_type']
KeyError: 'quest_type'
```

**Comment by LegitDongo** [comment]
It's been suggested that we change our current format to match the Poracle format, which is also the format RDM uses

I think this is a good idea, barring any problems

[see here for how it's implemented in MAD](https://github.com/Map-A-Droid/MAD/blob/89aebdb5f6f5817ce8a15f94d0129f6661e82f62/mapadroid/webhook/webhookworker.py#L179)

**Comment by billyjbryant** [comment]
This shouldn't be too difficult to manage. I will look to see if I can address it.
