### ISSUE TITLE
KeyError '1360' when starting

### ISSUE THREAD

**Issue by C64Axel** [pokealarm/pokealarm#885]
## Troubleshooting Checklist

- [x] My scanner install is at the most recent version.
- [x] My PokeAlarm install is at the most recent version.
- [x] I've already checked the [FAQ](https://pa.readthedocs.io/en/dev/getting-started/faq.html) and the [Wiki](https://pa.readthedocs.io/en/dev/) already.

## Problem Description
When starting pokealarm i get the following error:

```

2024-11-14 17:57:01,187 [CRITI][ pokealarm][ webserver] Missing PokeAlarm data
2024-11-14 17:59:24,425 [ INFO][ pokealarm][ webserver] Europe/Berlin
2024-11-14 17:59:25,142 [ INFO][ pokealarm][ webserver] New Masterfile data found! Fetching in progress...
2024-11-14 17:59:25,225 [ERROR][ pokealarm][ webserver] Unable to update PokeAlarm data: '1360'
2024-11-14 17:59:25,226 [DEBUG][ pokealarm][ webserver] Stack trace:
 Traceback (most recent call last):
  File "start_pokealarm.py", line 185, in check_for_update
    download_data()
  File "start_pokealarm.py", line 229, in download_data
    if masterfile_data["pokemon"]["255"]["forms"]["1360"]["name"] != "Purified":
KeyError: '1360'

2024-11-14 17:59:25,229 [CRITI][ pokealarm][ webserver] Missing PokeAlarm data

```

## Environment
Operating System: Ubuntu 20.04.6 LTS
Python Version: Python 3.8.10
PokeAlarm Version: 0efbaadf68b68cf018be1d710811f14daf697948
Scanner used: mad

Is there a solution to solve this error?

**Comment by Pontiky** [comment]
You can manually remove lines 229-230 in `start_pokealarm.py` file until a change is pushed.
https://github.com/pokealarm/pokealarm/blob/dev/start_pokealarm.py#L229-L230

**Comment by C64Axel** [comment]
Thank you. Worked.
Shoud we leave this issue open until the Problem ist solved?
I have searched for it but found nothing.

**Comment by Pontiky** [comment]
You can leave it open until the bug is fixed.
